# Generated by Django 3.2.16 on 2023-02-04 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_search'),
    ]

    operations = [
        migrations.AddField(
            model_name='search',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='search',
            name='number',
            field=models.IntegerField(max_length=100, null=True),
        ),
    ]
