# Generated by Django 3.2.16 on 2023-02-04 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_search_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='search',
            name='user',
        ),
    ]
