# Generated by Django 3.2.16 on 2023-02-04 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_remove_search_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='search',
            name='number',
            field=models.IntegerField(null=True),
        ),
    ]
